### ISSUE TITLE
How can make a compressed single html file out of this?

### ISSUE THREAD

**Issue by randy-shi** [than1089/adventure-capitalist#2]
I've seen in other games and repositories, some of them have build.js files, do you think you could make one for this one?

**Comment by than1089** [comment]
You can run `yarn build` to get the build version. The whole game won't be in an index.html file, it needs some javascript files to run. However, if you open index.html in the browser, it should work, like this one:

https://than1089.github.io/adventure-capitalist/index.html

**Comment by randy-shi** [comment]
This is the issue it gives me when I use `yarn build`
I think the issue is that it didn't create an `index.js` file.
I've already downloaded `babel-minify-webpack-plugin`, `webpack`, and `webpack-cli`
I've also already used `yarn install` and it did fine.
The path is there, so I don't understand what's going on.

yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ webpack --config webpack.prod.js
C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\babel-minify-webpack-plugin\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\webpack.prod.js:4:22)
    at Module._compile (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\yargs\yargs.js:576:18)
    at C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\maste\OneDrive\Downloads\advcapitalist-master\advcapitalist-master\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\maste\\OneDrive\\Downloads\\advcapitalist-master\\advcapitalist-master\\node_modules\\babel-minify-webpack-plugin\\package.json',
  requestPath: 'babel-minify-webpack-plugin'
}

Sorry for the questions, I'm not very familiar with this kind of stuff, and your replica is really good.
